name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:  
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: windows-latest
            runtime: win-x86
          - os: ubuntu-latest
            runtime: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime }} -p:PublishAot=true -o "${{github.workspace}}/package/dlls"

      - name: Create censor words file
        run: echo "fuck" > ${{github.workspace}}/package/censor_words.dic
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ChatEngine-${{ matrix.runtime }}
          path: |
            ${{github.workspace}}/package/

      - name: Zipping All
        if: matrix.os == 'windows-latest'
        uses: vimtor/action-zip@v1
        with:
            files: ${{github.workspace}}/package/dlls
            dest: ${{ matrix.os }}-${{ matrix.runtime }}.zip

      - name: Tarball All
        if: matrix.os != 'windows-latest'
        run: tar -czvf ./${{ matrix.os }}-${{ matrix.runtime }}.tar.gz "${{github.workspace}}/package/dlls"
      
      - name: Create Release Unix
        if: matrix.os != 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
            name: ${{ github.ref }}
            files: |
              ./${{ matrix.os }}-${{ matrix.runtime }}.tar.gz

      - name: Create Release Win
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
            name: ${{ github.ref }}
            files: |
              ${{ matrix.os }}-${{ matrix.runtime }}.zip